# Generated by Django 2.0.6 on 2018-06-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
