# Generated by Django 2.0.6 on 2018-06-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='popularity',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
