# Generated by Django 2.0.6 on 2018-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='popularity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
